### PR TITLE
CI: Upload Artifacts

### PR DESCRIPTION
**Pull request by Stanzilla**
Uploads build artifacts to the Github storage

### CODE REVIEW

**Comment by xanderfrangos** [comment]
Just to confirm: this won't automatically publish a new release, right?

**Comment by Stanzilla** [comment]
> Just to confirm: this won't automatically publish a new release, right?

Correct

**Comment by xanderfrangos** [comment]
Awesome. Looks like you might still be playing with the settings, so let me know once you think this CI process is good to go and I'll merge it in.

**Comment by Stanzilla** [comment]
It is done now, since the CI only does the Windows version, filtering to the .exe is ok. If you also want CI for mac, that can be a new PR.

**Comment by xanderfrangos** [comment]
OK, merging now. Thanks for this!

A Mac version would be great. I can add a certificate for Mac signing. I'd just need to know what to name the secret.

**Pull request merged**
